name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - uses: danger/swift@2.0.1
      - name: Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
