name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@optimise_danger_action_clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
